name: Post Release Workflow

run-name: Post Release -- ${{github.ref_name}}

on:
    push:
        tags: '**'

jobs:
    post_release:
        name: Create Release & Publish
        runs-on: ubuntu-24.04
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4
      
          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'zulu'
              java-version: '21'
              server-id: ossrh
              server-username: MAVEN_USERNAME
              server-password: MAVEN_CENTRAL_TOKEN
              gpg-private-key: ${{secrets.GPG_KEY}}
              gpg-passphrase: MAVEN_GPG_PASSPHRASE

          - name: Maven Build
            run: |
             ./mvnw clean install -U \
              --batch-mode \
              -e \
              -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
              -Dmaven.build.cache.enabled=false \
      
          - name: Publish To OSSRH (Maven Central Staging)
            shell: bash
            run: |
                ./mvnw deploy -U\
                    --batch-mode \
                    -e \
                    -U \
                    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                    -DskipTests \
                    -DskipITs \
                    -Dmaven.main.skip \
                    -Dmaven.test.skip \
                    -DrepositoryId=ossrh \
                    -DrepositoryIdOSSRH='true' \
                    -PstageOSSRH \
                    -Dmaven.build.cache.enabled=false
            env:
              MAVEN_USERNAME: ${{secrets.OSSRH_TOKEN_USER}}
              MAVEN_CENTRAL_TOKEN: ${{secrets.OSSRH_TOKEN_PASS}}
              MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}

          - name: Create Release
            id: create_release
            run: |
                    curl -L \
                     -X POST \
                     -H "Accept: application/vnd.github+json" \
                     -H "Authorization: Bearer ${{secrets.GITHUB_TOKEN}}" \
                     -H "X-GitHub-Api-Version: 2022-11-28" \
                     https://api.github.com/repos/${{github.repository}}/releases \
                    -d '{"tag_name":"${{github.ref_name}}","name":"Release ${{github.ref_name}}","body":"Release ${{github.ref_name}}","draft":false,"prerelease":false,"generate_release_notes":false}'